package com.ashutosh.urban_cravin.models.orderFlow;

import com.ashutosh.urban_cravin.helpers.enums.PaymentStatus;
import com.ashutosh.urban_cravin.models.orderFlow.Order;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.util.UUID;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "payments")
public class Payment {
    @Id
    @GeneratedValue
    @JdbcTypeCode(SqlTypes.CHAR)
    @Column(length = 36, nullable = false)
    private UUID id;

    @OneToOne
    @JoinColumn(name = "order_id", nullable = false)
    private Order order;

    private String transactionId; // generated by you (merchantTxnId)
    private String providerReferenceId; // PhonePe transaction ref

    @Enumerated(EnumType.STRING)
    private PaymentStatus status;

    private Double amount;
}
