spring:
  task:
    scheduling:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name
    username: your_username
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  webclient:
    timeout: 30s

server:
  port: 8080
  servlet:
    context-path: /

# PhonePe Configuration
phonepe:
  merchant-id: YOUR_MERCHANT_ID
  api-key: YOUR_SALT_KEY  # This is your Salt Key from PhonePe dashboard
  key-index: 1
  redirect-url: http://localhost:8080/payment/redirect
  callback-url: http://localhost:8080/api/payments/webhook
  base-url: https://api.phonepe.com  # For production
  # base-url: https://api-preprod.phonepe.com  # For sandbox/testing

# JWT Configuration
jwt:
  secret: 2U9ZV7yQaPQWkR3CMkhy7urJYl3cDPD8OHS8lt6GJfs=
  expiration: 3600000

# File Upload
upload:
  path: ${user.dir}/uploads

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      phonepeCircuitBreaker:
        register-health-indicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
  retry:
    instances:
      phonepeRetry:
        max-attempts: 3
        wait-duration: 2s

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,circuitbreakers
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# Logging Configuration
logging:
  level:
    com.ashutosh.urban_cravin: DEBUG
    com.ashutosh.urban_cravin.services.payment: DEBUG
    org.springframework.web.reactive.function.client: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
  file:
    name: logs/urban-cravin.log

#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#
#server:
#  port: 8080
#
#jwt:
#  secret: 2U9ZV7yQaPQWkR3CMkhy7urJYl3cDPD8OHS8lt6GJfs=
#  expiration: 3600000
#
#upload:
#  path: ${user.dir}/uploads
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,prometheus
#  endpoint:
#    prometheus:
#      enabled: true
#  metrics:
#    export:
#      prometheus:
#        enabled: true