spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

jwt:
  secret: 2U9ZV7yQaPQWkR3CMkhy7urJYl3cDPD8OHS8lt6GJfs=
  expiration: 3600000

upload:
  path: ${user.dir}/uploads

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true