spring:
  datasource:
    url: jdbc:mysql://mysql:3306/urban_cravin_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: urban_cravin
    password: Cravin@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  redis:
    host: redis
    port: 6379

server:
  port: 8080

jwt:
  secret: 2U9ZV7yQaPQWkR3CMkhy7urJYl3cDPD8OHS8lt6GJfs=
  expiration: 3600000

upload:
  path: ${user.dir}/uploads
